package org.tg.domain;

public enum BonsaiEstilo {
    
    HOKIDACHIVASSOURA, CHOKKANERETOFORMAL, MOYOGIERETOINFORMAL, SHAKANINCLINADOOUOBLIQUO, KENGAICASCATA, HANKENGAISEMICASCATA, BUNJINGILITERATI, FUKINAGASHIVARRIDOPELOVENTO, SOKANTRONCODUPLO, KABUDACHIMULTIPLOSTRONCOS, YOSEUEFLORESTA, SEKIJOJURAIZABRACADAAROCHA, ISHISUKICRESCIMENTOEMROCHA, IKADABUKIBALSA, SHARIMIKIMADEIRAMORTA;
}
